### ISSUE TITLE
Multiple line charts/bar charts on same page

### ISSUE THREAD

**Issue by HamptonNorth** [Ajiva-D/vuecharts#1]
Thank you for this clear and easy to understand code sample. 
It does not however support multiple <line-chart> or <bar-chart> components on the same page as there is no unique id for the canvas element.
I've got the code change needed.
Are you looking to enhance or was this a quick one off for the article?

Let me know

Rob

**Comment by Ajiva-D** [comment]
Hello Rob, this example was just for the article but I'm open to enhancements as it could help others too.
Please feel free to open a PR on this, thank you.
